/**
 * Brainy Hearts - A Multifunctional App
 * @version 12.0.0 FINAL
 */
const brainyHeartsApp = {
    // --- 1. CONFIGURATION & CONTENT ---
    config: {
        typewriterSpeed: 40, iqTimeLimit: 15,
        iqQuestions: [ { question: "Which number should come next in the pattern? 1, 1, 2, 3, 5, ...", options: ["8", "7", "6", "10"], correct: "8" }, { question: "A is the father of B. But B is not the son of A. How is that possible?", options: ["A is an uncle", "B is a daughter", "B is adopted", "A is a step-father"], correct: "B is a daughter" }, { question: "What has an eye, but cannot see?", options: ["A storm", "A potato", "A needle", "A hurricane"], correct: "A needle" }, { question: "If you have a bowl with six apples and you take away four, how many do you have?", options: ["Two", "Six", "Four", "None"], correct: "Four" }, { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correct: "Canberra" }, { question: "How many months have 28 days?", options: ["1", "2", "All of them", "Depends on the year"], correct: "All of them" }, { question: "A farmer had 17 sheep. All but nine died. How many are left?", options: ["17", "8", "9", "0"], correct: "9" }, { question: "What occurs once in a minute, twice in a moment, but never in a thousand years?", options: ["The number 0", "The letter 'M'", "A leap second", "A solar eclipse"], correct: "The letter 'M'" } ],
        lifeAdvice: [ "The best love is the kind that awakens the soul and makes us reach for more.", "True love is not found, it is built. Day by day, moment by moment.", "A successful relationship requires falling in love many times, always with the same person.", "Listen with curiosity. Speak with honesty. Act with integrity.", "The greatest happiness is to know the source of unhappiness.", "Patience is not the ability to wait, but the ability to keep a good attitude while waiting.", "Shared laughter is one of the most essential ingredients of a happy relationship.", "Growth is a process. Be kind to yourself and your partner along the journey.", "Before you can love another, you must first learn to love yourself.", "Communication is the fuel that keeps the fire of a relationship burning." ],
        poetry: [ "You are my sun, my moon, and all my stars.", "In your light, I learn how to love.", "We are two souls, but with a single thought; two hearts that beat as one.", "My heart is, and always will be, yours.", "I would rather spend one lifetime with you, than face all the ages of this world alone.", "If I know what love is, it is because of you.", "Your hand touching mine. This is how galaxies collide.", "Love is a friendship set to music." ],
        famousPoetry: [ { author: "William Shakespeare", text: "Doubt thou the stars are fire; Doubt that the sun doth move; Doubt truth to be a liar; But never doubt I love." }, { author: "Elizabeth Barrett Browning", text: "How do I love thee? Let me count the ways. I love thee to the depth and breadth and height My soul can reach." }, { author: "Pablo Neruda", text: "I love you without knowing how, or when, or from where. I love you simply, without problems or pride." }, { author: "Rumi", text: "The minute I heard my first love story, I started looking for you, not knowing how blind that was. Lovers don't finally meet somewhere. They're in each other all along." } ]
    },
    elements: {}, iqScore: 0, currentIQQuestionIndex: 0, iqTimer: null, currentShuffledIQ: [],

    // --- 2. INITIALIZATION ---
    init() { this.cacheDOMElements(); this.bindEvents(); this.handleSplashScreen(); this.loadTheme(); },
    handleSplashScreen() { const splashScreen = this.elements.splashScreen; if (splashScreen) { window.addEventListener('load', () => { splashScreen.classList.add('hidden'); setTimeout(() => { splashScreen.style.display = 'none'; }, 750); }); } },
    cacheDOMElements() { this.elements = { splashScreen: document.getElementById('splash-screen'), startScreen: document.getElementById('start-screen'), startSoulmatesBtn: document.getElementById('startSoulmatesBtn'), startIQBtn: document.getElementById('startIQBtn'), soulmatesScreen: document.getElementById('soulmates-screen'), iqTestScreen: document.getElementById('iq-test-screen'), iqResultScreen: document.getElementById('iq-result-screen'), homeBtn: document.getElementById('homeBtn'), iqQuitBtn: document.getElementById('iq-quit-btn'), name1: document.getElementById("name1"), bday1: document.getElementById("bday1"), country1: document.getElementById("country1"), sport1: document.getElementById("sport1"), name2: document.getElementById("name2"), bday2: document.getElementById("bday2"), country2: document.getElementById("country2"), sport2: document.getElementById("sport2"), calculateBtn: document.getElementById("calculateBtn"), resetBtn: document.getElementById("resetBtn"), resultDiv: document.getElementById("result"), themeToggle: document.getElementById("themeToggle"), iqThemeToggle: document.getElementById("iq-theme-toggle"), rewardRevealModal: document.getElementById('reward-reveal-modal'), closeRewardBtn: document.getElementById('closeRewardBtn'), rewardTitle: document.getElementById('reward-title'), rewardEmoji: document.getElementById('reward-emoji'), rewardText: document.getElementById('reward-text'), iqQuestionCounter: document.getElementById('iq-question-counter'), iqTimerDisplay: document.getElementById('iq-timer'), iqQuestionText: document.getElementById('iq-question-text'), iqOptionsContainer: document.getElementById('iq-options-container'), iqFinalScore: document.getElementById('iq-final-score'), iqResultMessage: document.getElementById('iq-result-message'), brainAnalysis: document.getElementById('brain-analysis'), brainAnalysisEmoji: document.getElementById('brain-analysis-emoji'), brainAnalysisText: document.getElementById('brain-analysis-text'), iqRestartBtn: document.getElementById('iq-restart-btn'), iqBackToHomeBtn: document.getElementById('iq-back-to-home-btn'), clickSound: document.getElementById("clickSound"), celebrationSound: document.getElementById("celebrationSound"), perfectMatchSound: document.getElementById("perfectMatchSound"), rewardUnlockSound: document.getElementById("rewardUnlockSound") }; },
    bindEvents() { this.elements.startSoulmatesBtn.addEventListener('click', () => this.showScreen('soulmates-screen')); this.elements.startIQBtn.addEventListener('click', () => this.startIQTest()); this.elements.homeBtn.addEventListener('click', () => this.showScreen('start-screen')); this.elements.iqQuitBtn.addEventListener('click', () => this.showScreen('start-screen')); this.elements.calculateBtn.addEventListener("click", this.handleCalculateClick.bind(this)); this.elements.resetBtn.addEventListener("click", this.resetCalculator.bind(this)); this.elements.themeToggle.addEventListener("click", this.toggleDarkMode.bind(this)); this.elements.iqThemeToggle.addEventListener("click", this.toggleDarkMode.bind(this)); this.elements.closeRewardBtn.addEventListener('click', this.closeRewardModal.bind(this)); this.elements.rewardRevealModal.addEventListener('click', (e) => { if (e.target === this.elements.rewardRevealModal) this.closeRewardModal(); }); this.elements.iqRestartBtn.addEventListener('click', () => this.startIQTest()); this.elements.iqBackToHomeBtn.addEventListener('click', () => this.showScreen('start-screen')); },

    // --- 3. SCREEN & FLOW MANAGEMENT ---
    showScreen(screenId) { this.playSound(this.elements.clickSound); clearInterval(this.iqTimer); ['start-screen', 'soulmates-screen', 'iq-test-screen', 'iq-result-screen'].forEach(id => { document.getElementById(id).classList.add('hidden'); }); document.getElementById(screenId).classList.remove('hidden'); },
    handleCalculateClick() { this.playSound(this.elements.clickSound); const inputs = this.getInputs(); if (!this.validateInputs(inputs)) { this.showError("Please fill in name and birthdate! 😅"); return; } this.elements.calculateBtn.disabled = true; this.startCountdown(inputs); },
    
    // --- 4. IQ TEST LOGIC ---
    shuffleArray(array) { for (let i = array.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [array[i], array[j]] = [array[j], array[i]]; } return array; },
    startIQTest() { this.showScreen('iq-test-screen'); this.iqScore = 0; this.currentIQQuestionIndex = 0; this.currentShuffledIQ = this.shuffleArray([...this.config.iqQuestions]).slice(0, 5); this.displayNextIQQuestion(); },
    displayNextIQQuestion() { if (this.currentIQQuestionIndex >= this.currentShuffledIQ.length) { this.showIQResults(); return; } const question = this.currentShuffledIQ[this.currentIQQuestionIndex]; this.elements.iqQuestionCounter.textContent = `Question ${this.currentIQQuestionIndex + 1}/${this.currentShuffledIQ.length}`; this.elements.iqQuestionText.textContent = question.question; this.elements.iqOptionsContainer.innerHTML = ''; question.options.forEach(option => { const button = document.createElement('button'); button.textContent = option; button.className = 'iq-option-btn'; button.addEventListener('click', () => this.handleIQAnswer(option, button)); this.elements.iqOptionsContainer.appendChild(button); }); this.startIQTimer(); },
    startIQTimer() { clearInterval(this.iqTimer); let timeLeft = this.config.iqTimeLimit; this.elements.iqTimerDisplay.textContent = `${timeLeft}s`; this.iqTimer = setInterval(() => { timeLeft--; this.elements.iqTimerDisplay.textContent = `${timeLeft}s`; if (timeLeft <= 0) { clearInterval(this.iqTimer); this.handleIQAnswer(null); } }, 1000); },
    handleIQAnswer(selectedOption, clickedButton) { clearInterval(this.iqTimer); const question = this.currentShuffledIQ[this.currentIQQuestionIndex]; Array.from(this.elements.iqOptionsContainer.children).forEach(button => { button.disabled = true; if (button.textContent === question.correct) { button.classList.add('correct'); } }); if (selectedOption === question.correct) { this.iqScore++; } else if (clickedButton) { clickedButton.classList.add('incorrect'); } setTimeout(() => { this.currentIQQuestionIndex++; this.displayNextIQQuestion(); }, 1500); },
    showIQResults() { this.showScreen('iq-result-screen'); const scorePercent = (this.iqScore / this.currentShuffledIQ.length) * 100; this.elements.iqFinalScore.textContent = `${scorePercent}%`; let message, brainType, brainEmoji; if (scorePercent === 100) { message = "Perfect Score! Certified Genius!"; brainType = "A Perfectly Balanced Brain!"; brainEmoji = "🧠"; setTimeout(() => this.revealReward('einstein'), 500); } else if (scorePercent >= 80) { message = "Excellent! Very Sharp!"; brainType = "A Dominantly Logical Left-Brain!"; brainEmoji = "🧩"; } else if (scorePercent >= 40) { message = "Good effort! A Solid Thinker."; brainType = "A Wonderfully Creative Right-Brain!"; brainEmoji = "🎨"; } else { message = "Nice try! Keep practicing!"; brainType = "A Mind Full of Potential!"; brainEmoji = "🌱"; } this.elements.iqResultMessage.textContent = message; this.elements.brainAnalysisEmoji.textContent = brainEmoji; this.elements.brainAnalysisText.textContent = brainType; },

    // --- 5. SOULMATES CALCULATOR LOGIC ---
    getInputs() { return { name1: this.elements.name1.value.trim(), bday1: this.elements.bday1.value, name2: this.elements.name2.value.trim(), bday2: this.elements.bday2.value, }; },
    validateInputs(inputs) { return inputs.name1 && inputs.name2 && inputs.bday1 && inputs.bday2; },
    closeRewardModal() { this.elements.rewardRevealModal.classList.add('hidden'); },
    revealReward(rewardType) { let title, emoji, content; if (rewardType === 'einstein') { title = 'A Spark of Genius!'; emoji = '💡'; content = `"The true sign of intelligence is not knowledge but imagination."<br><br>- Albert Einstein`; } else if (rewardType === 100) { const famousQuote = this.config.famousPoetry[Math.floor(Math.random() * this.config.famousPoetry.length)]; title = 'A Poetic Masterpiece!'; emoji = '📜'; content = `"${famousQuote.text}"<br><br>- ${famousQuote.author}`; } else { if (Math.random() > 0.5) { title = 'A Spark of Wisdom!'; emoji = '💡'; content = this.config.lifeAdvice[Math.floor(Math.random() * this.config.lifeAdvice.length)]; } else { title = 'A Verse for the Heart!'; emoji = '✒️'; content = this.config.poetry[Math.floor(Math.random() * this.config.poetry.length)]; } } this.elements.rewardTitle.textContent = title; this.elements.rewardEmoji.textContent = emoji; this.elements.rewardText.innerHTML = content; this.elements.rewardRevealModal.classList.remove('hidden'); this.playSound(this.elements.rewardUnlockSound); },
    getZodiacSign(dateString) { if (!dateString) return "Unknown ❓"; const date = new Date(dateString); const month = date.getMonth() + 1; const day = date.getDate(); if ((month === 1 && day >= 20) || (month === 2 && day <= 18)) return "Aquarius ♒"; if ((month === 2 && day >= 19) || (month === 3 && day <= 20)) return "Pisces ♓"; if ((month === 3 && day >= 21) || (month === 4 && day <= 19)) return "Aries ♈"; if ((month === 4 && day >= 20) || (month === 5 && day <= 20)) return "Taurus ♉"; if ((month === 5 && day >= 21) || (month === 6 && day <= 20)) return "Gemini ♊"; if ((month === 6 && day >= 21) || (month === 7 && day <= 22)) return "Cancer ♋"; if ((month === 7 && day >= 23) || (month === 8 && day <= 22)) return "Leo ♌"; if ((month === 8 && day >= 23) || (month === 9 && day <= 22)) return "Virgo ♍"; if ((month === 9 && day >= 23) || (month === 10 && day <= 22)) return "Libra ♎"; if ((month === 10 && day >= 23) || (month === 11 && day <= 21)) return "Scorpio ♏"; if ((month === 11 && day >= 22) || (month === 12 && day <= 21)) return "Sagittarius ♐"; return "Capricorn ♑"; },
    getLoveResult(name1, name2) { const n1Lower = name1.toLowerCase(); const n2Lower = name2.toLowerCase(); if ((n1Lower === "umer" && n2Lower === "huma") || (n1Lower === "huma" && n2Lower === "umer")) { return { score: 100, message: "A match written in the stars! 💍", emoji: "💍" }; } const combined = (name1 + name2).toLowerCase().replace(/\s/g, ''); let seed = 0; for (let i = 0; i < combined.length; i++) { seed = (seed + combined.charCodeAt(i) * (i + 1)) % 101; } const score = Math.floor(seed * 0.6) + 40; if (score > 80) return { score, message: "A Perfect Match! 🔥 You two are inseparable!", emoji: "💘" }; if (score >= 60) return { score, message: "Looks very promising! 💖 Keep the flame alive.", emoji: "💖" }; if (score < 50) return { score, message: "A connection to work on... 💔", emoji: "💔" }; return { score, message: "There's potential... with a little work. 😉", emoji: "🤔" }; },
    resetCalculator() { ['name1', 'bday1', 'country1', 'sport1', 'name2', 'bday2', 'country2', 'sport2'].forEach(id => this.elements[id].value = ''); this.elements.resultDiv.innerHTML = ""; this.elements.calculateBtn.disabled = false; this.playSound(this.elements.clickSound); },
    startCountdown(inputs) { this.elements.resultDiv.innerHTML = `<h2>Calculating...</h2>`; let count = 3; const interval = setInterval(() => { if (count > 0) { this.elements.resultDiv.innerHTML = `<h2 style="font-size: 3em; animation: pulse 0.5s ease-out;">${count}</h2>`; count--; } else { clearInterval(interval); const result = this.getLoveResult(inputs.name1, inputs.name2); this.displayResult(inputs, result); } }, 800); },
    displayResult(inputs, result) { const sign1 = this.getZodiacSign(inputs.bday1); const sign2 = this.getZodiacSign(inputs.bday2); this.elements.resultDiv.innerHTML = ` <p><strong>${inputs.name1}</strong> (${sign1}) & <strong>${inputs.name2}</strong> (${sign2})</p> <div class="progress-container"> <div id="progressBar"></div> </div> <p id="result-message" style="opacity:0;"></p> <div id="reward-prompt"></div> `; setTimeout(() => { document.getElementById("progressBar").style.width = result.score + '%'; }, 100); const finalMessage = `${result.emoji} ${result.score}% - ${result.message}`; this.typeWriter(finalMessage, document.getElementById('result-message'), () => { this.elements.calculateBtn.disabled = false; const rewardPromptDiv = document.getElementById('reward-prompt'); if (result.score > 80) { this.playSound(result.score === 100 ? this.elements.perfectMatchSound : this.elements.celebrationSound); this.launchConfetti(); this.explodeHearts(); rewardPromptDiv.innerHTML = `<p>You have won a reward!</p><button class="open-reward-btn">Click to Open</button>`; rewardPromptDiv.querySelector('.open-reward-btn').addEventListener('click', () => this.revealReward(result.score)); } else if (result.score < 50) { rewardPromptDiv.innerHTML = `<p class="sorry-message">Sorry, no reward this time. Try for a higher score!</p>`; } }); },
    showError(message) { this.elements.resultDiv.innerHTML = `<p style="color: red;">${message}</p>`; },
    typeWriter(text, element, callback) { if (!element) return; element.style.opacity = 1; let i = 0; const type = () => { if (i < text.length) { element.innerHTML += text.charAt(i); i++; setTimeout(type, this.config.typewriterSpeed); } else if (callback) { callback(); } }; type(); },

    // --- 7. THEME MANAGEMENT & UTILITIES ---
    toggleDarkMode() { const isDark = document.body.classList.toggle("dark-mode"); const newIcon = isDark ? "☀️" : "🌙"; [this.elements.themeToggle, this.elements.iqThemeToggle].forEach(btn => { if(btn) btn.textContent = newIcon; }); localStorage.setItem('theme', isDark ? 'dark' : 'light'); },
    loadTheme() { if (localStorage.getItem('theme') === 'dark') { document.body.classList.add('dark-mode'); [this.elements.themeToggle, this.elements.iqThemeToggle].forEach(btn => { if(btn) btn.textContent = "☀️"; }); } },
    playSound(sound) { if (sound) { sound.currentTime = 0; sound.play().catch(e => console.error("Audio playback failed:", e)); } },
    launchConfetti() { if (typeof confetti === 'function') { confetti({ particleCount: 200, spread: 100, origin: { y: 0.6 } }); } },
    explodeHearts() { for (let i = 0; i < 30; i++) { const heart = document.createElement("div"); heart.innerHTML = ["❤️", "💖", "💕", "💗"][Math.floor(Math.random() * 4)]; heart.className = 'heart'; heart.style.left = Math.random() * 100 + "vw"; heart.style.animationDuration = Math.random() * 2 + 3 + "s"; heart.style.fontSize = Math.random() * 20 + 15 + "px"; document.body.appendChild(heart); setTimeout(() => heart.remove(), 5000); } },
};

brainyHeartsApp.init();